DEFINE TABLESPACE = &&1
SET VERIFY OFF


DROP TABLESPACE "&&TABLESPACE"
    INCLUDING CONTENTS AND DATAFILES
     CASCADE CONSTRAINTS

PROMPT &&TABLESPACE WAS DROPED

SET VERIFY ON;
UNDEFINE TABLESPACE