DEFINE DATA_TBSP_NAME = &&1;
DEFINE DATA_TBSP_LOCATION = &&2;
DEFINE INDEX_TBSP_NAME = &&3;
DEFINE INDEX_TBSP_LOCATION = &&4;
SET VERIFY OFF;

CREATE TABLESPACE &&DATA_TBSP_NAME 
    DATAFILE 
        '&&DATA_TBSP_LOCATION\\&&DATA_TBSP_NAME..dbf' 
        SIZE 10M AUTOEXTEND ON NEXT 10 MAXSIZE 5368709120

PROMPT &&DATA_TBSP_LOCATION\\&&DATA_TBSP_NAME..dbf was created

CREATE SMALLFILE TABLESPACE &&INDEX_TBSP_NAME 
    DATAFILE 
        '&&INDEX_TBSP_LOCATION\\&&INDEX_TBSP_NAME..dbf' 
        SIZE 10M AUTOEXTEND ON NEXT 10 MAXSIZE 5368709120       

PROMPT &&INDEX_TBSP_LOCATION\\&&INDEX_TBSP_NAME..dbf was created

        
UNDEFINE DATA_TBSP_NAME
UNDEFINE DATA_TBSP_LOCATION
UNDEFINE INDEX_TBSP_NAME
UNDEFINE INDEX_TBSP_LOCATION
SET VERIFY ON
--C:\_programs\oradata\ORCL