DEFINE USER = &&1;
SET VERIFY OFF;

ALTER USER "&&USER"
DEFAULT TABLESPACE "&&USER._TABLESPACE"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE ANY DIRECTORY TO "&&USER" WITH ADMIN OPTION;
GRANT BECOME USER TO "&&USER" WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO "&&USER" WITH ADMIN OPTION;
GRANT SELECT ANY TRANSACTION TO "&&USER" WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO "&&USER" WITH ADMIN OPTION;
GRANT ALTER ANY INDEX TO "&&USER" WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO "&&USER" WITH ADMIN OPTION;


SET VERIFY ON;
UNDEFINE USER;


