delete from department;
delete from employee;
delete from employee_role;
delete from employee_skill
delete from role;
delete from skill;
delete from team;
delete from project;
delete from stage;
delete from task;